#!/usr/bin/python3
import unittest
from models.base_model import BaseModel

class TestBaseModel(unittest.TestCase):
    """TestBaseModel class to test the BaseModel class."""
    
    def test_create_instance(self):
        """Test creating an instance of BaseModel."""
        my_model = BaseModel()
        self.assertIsInstance(my_model, BaseModel)

if __name__ == "__main__":
    unittest.main()
